Importing the Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Importing the Dataset

In [3]:
dataset = pd.read_csv(r'C:\Users\hp\Downloads\Machine Learning\GetFreeCourses.Co-Udemy-Machine Learning A-Z™ Python & R in Data Science [2023]\23 - Classification Model Selection in Python\Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

Splitting the Dataset into Training Set and Test Set

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

Feature Scaling

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Logistic Regression

In [12]:
from sklearn.linear_model import LogisticRegression
cl1 = LogisticRegression()
cl1.fit(X_train, y_train)

LogisticRegression()

In [22]:
y1 = cl1.predict(X_test)

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y1, y_test))
print(accuracy_score(y1, y_test))

[[103   5]
 [  4  59]]
0.9473684210526315


K Nearest Neighbors

In [28]:
from sklearn.neighbors import KNeighborsClassifier
cl2 = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
cl2.fit(X_train, y_train)

KNeighborsClassifier()

In [29]:
y2 = cl2.predict(X_test)

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y2, y_test))
print(accuracy_score(y2, y_test))

[[103   5]
 [  4  59]]
0.9473684210526315


SVM

In [35]:
from sklearn.svm import SVC
cl3 = SVC(kernel = 'linear', random_state = 0)
cl3.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [36]:
y3 = cl3.predict(X_test)

In [37]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y3, y_test))
print(accuracy_score(y3, y_test))

[[102   5]
 [  5  59]]
0.9415204678362573


SVM Kernel

In [39]:
from sklearn.svm import SVC
cl4 = SVC(kernel = 'rbf', random_state = 0)
cl4.fit(X_train, y_train)

SVC(random_state=0)

In [40]:
y4 = cl4.predict(X_test)

In [41]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y4, y_test))
print(accuracy_score(y4, y_test))

[[102   3]
 [  5  61]]
0.9532163742690059


Naive Bayes

In [42]:
from sklearn.naive_bayes import GaussianNB
cl5 = GaussianNB()
cl5.fit(X_train, y_train)

GaussianNB()

In [43]:
y5 = cl5.predict(X_test)

In [44]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y5, y_test))
print(accuracy_score(y5, y_test))

[[99  2]
 [ 8 62]]
0.9415204678362573


Decision Tree Classification

In [72]:
from sklearn.tree import DecisionTreeClassifier
cl6 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
cl6.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [73]:
y6 = cl6.predict(X_test)

In [74]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y6, y_test))
print(accuracy_score(y6, y_test))

[[103   3]
 [  4  61]]
0.9590643274853801


Random Forest Classification

In [69]:
from sklearn.ensemble import RandomForestClassifier
cl7 = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
cl7.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [70]:
y7 = cl7.predict(X_test)

In [71]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y7, y_test))
print(accuracy_score(y7, y_test))

[[102   6]
 [  5  58]]
0.935672514619883
