Importing the Libraries

In [46]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [47]:
tf.__version__

'2.12.0'

<H3>Part - 1 : Data Preprocessing</H3>

Importing the Dataset

In [48]:
dataset = pd.read_csv(r'C:\Users\hp\Downloads\Machine Learning\Machine Learning A-Z (Codes and Datasets)\Part 8 - Deep Learning\Section 39 - Artificial Neural Networks (ANN)\Python\Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

Encoding Categorical Data

Label Encoding the "Gender" column

In [49]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [50]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

One Hot Encoding the "Geography" column

In [51]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [52]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

Splitting the Dataset into the Training Set and the Test Set

In [53]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

Feature Scaling

In [60]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

<H3>Part - 2 : Building the ANN</H3>

Initializing the ANN

In [61]:
ann = tf.keras.models.Sequential()

Adding the Input Layer and the First Hidden Layer

In [62]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

Adding the Second Hidden Layer

In [63]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

Adding the Output Layer

In [64]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

<H3>Part - 3 : Training the ANN</H3>

Compiling the ANN

In [65]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Training the ANN on the Training Set

In [66]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 2ms/step - loss: 0.6006 - accuracy: 0.7182
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4948 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4576 - accuracy: 0.7969
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4411 - accuracy: 0.7997
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4332 - accuracy: 0.8033
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4273 - accuracy: 0.8094
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4221 - accuracy: 0.8150
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4178 - accuracy: 0.8195
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4137 - accuracy: 0.8211
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4100 - accura

<H3>Part - 4 : Making Predictions and Evaluating the Model</H3>

Predicting the Result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

In [68]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 210ms/step
[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

Predicting the Test Result

In [71]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Making the Confusion Matrix

In [72]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1520   75]
 [ 206  199]]


0.8595